<a href="https://colab.research.google.com/github/abdulaziz2501/Edfix_vazifalari/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np

np.version
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [11]:
lst=list()
for i in range(25):
  lst.append(i)
arr=np.array(lst)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [12]:
arr1=np.zeros(9)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [16]:
arr=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])
print(arr.itemsize)
print(arr.size)

8
25


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [19]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [22]:
arr2=np.eye(12)[5]
arr2

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [24]:
arr3=np.arange(20,60)
arr3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [26]:
arr3=np.arange(20,60)
arr3[::-1]

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [28]:
arr4=np.arange(12,21).reshape(3,3)
arr4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [30]:
arr5=np.array([3, 7, 0, 0, 9, 0])
arr5.nonzero()

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [32]:
arr6=np.random.randn(2,2,2)
arr6

array([[[ 0.27445892, -0.57418961],
        [ 0.5545754 , -0.68497594]],

       [[-0.57503422, -0.92122848],
        [ 1.14281395,  0.91532652]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [45]:
arr6=np.random.randint(10, size=(9,9))
print(arr6)
print(arr6.min())
print(arr6.max())

[[6 1 4 6 3 6 7 1 1]
 [4 8 6 0 0 2 5 4 0]
 [4 5 9 4 9 4 3 9 4]
 [9 6 6 5 4 9 0 8 2]
 [3 1 3 3 3 3 2 4 7]
 [8 2 2 5 8 1 6 4 1]
 [5 6 7 8 0 7 3 0 4]
 [3 1 1 1 1 1 6 6 5]
 [3 0 3 1 9 8 5 6 8]]
0
9


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [46]:
0 * np.nan         # nan - NaN bilan har qanday arifmetik amal NaN qaytaradi
np.nan == np.nan   # False - NaN o'ziga teng emas
np.inf > np.nan    # False - NaN bilan har qanday taqqoslash False qaytaradi
np.nan - np.nan    # nan - NaN bilan har qanday arifmetik amal NaN qaytaradi
np.nan in set([np.nan]) # True - Pythonda set NaN ni maxsus ko'rib chiqadi
0.7 == 7 * 0.1     # False - Floating-point xatolik tufayli

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.7 == 7 * 0.1)

nan
False
False
nan
True
False


#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [48]:
arr1=np.random.randint(18, size=(6,3))
arr2=np.random.randint(12, size=(3,4))
print(arr1.dot(arr2))

[[ 76  78 104 202]
 [ 86  85  73 228]
 [110 111 193 279]
 [ 22  35  41  91]
 [ 18  77 129 191]
 [ 90  99 195 244]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [63]:
print(sum(range(5),-1)) # BU yerda python kutubxonasini standart funksiyalaridan sum ishlaydi, unda sum(a, b)qiymatlarini yigindisini qaytaradi
# range(5) 10ga teng unga + (-1) bo'lib qiymat 9 bo'lladi
from numpy import *
print(sum(range(5),-1)) # Bu yerda numpy dagi sum funksiaysi ishlaydi undagi 2- qiymat (b) axis o'q sifatida kelgani uchun qiymat 10 bo'lib qoladi.

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [65]:
a=np.array([1,2])
b=np.array([4,5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)


[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [70]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-70-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-70-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-70-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [71]:
arr1=np.array([1, 3, 5, 7, 9, 11])
arr2=np.array([2, 3, 5, 8, 9, 10])
print(np.intersect1d(arr1, arr2))

[3 5 9]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [112]:
arr=np.random.randint(15, size=(10))
a=arr-arr%12
b=np.floor(arr)
c=arr.astype(int)
d=np.trunc(arr)


print("\n1-usul (%):", a)
print("\n2-usul (floor):", b)
print("\n3-usul (astype):", c)
print("\n4-usul (trunc):", d)


1-usul (%): [ 0 12  0  0  0  0  0  0 12 12]

2-usul (floor): [ 5. 14.  8.  8.  0.  4.  4.  1. 12. 13.]

3-usul (astype): [ 5 14  8  8  0  4  4  1 12 13]

4-usul (trunc): [ 5. 14.  8.  8.  0.  4.  4.  1. 12. 13.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [2]:
num=np.arange(3)
arr=np.array([num, num, num])
arr


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [5]:
arr=np.random.randint(15, size=10)
arr.sort()
arr

array([ 2,  3,  4,  6,  8,  9,  9, 10, 10, 14])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [21]:
a=np.random.randint(15, size=10)
b=np.random.randint(12, size=10)
print("\n1. np.array_equal() natijasi:", np.array_equal(a, b))
print("\n1. np.array_allclose() natijasi:", np.allclose(a, b))



1. np.array_equal() natijasi: False

1. np.array_allclose() natijasi: False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [24]:
arr1=np.random.randint(15, size=(6,3))
arr2=np.random.randint(12, size=(3,4))
print(arr1.dot(arr2))

[[ 94 159 252 122]
 [ 89 115 168  85]
 [ 33  79 130  64]
 [125  89  64  65]
 [162 137 136 100]
 [ 73 110 166  84]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [43]:
a=np.random.randint(15, size=10)
print(a)
a[a.argmax()] = 0
print(a[a.argmax()])
print(a)


[13  0  8 10  4  0  5 14 14  9]
14
[13  0  8 10  4  0  5  0 14  9]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [44]:
bugun = np.datetime64('today')
kecha = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')

print("Kecha:", kecha)
print("Bugun:", bugun)
print("Ertaga:", ertaga)

Kecha: 2025-05-07
Bugun: 2025-05-08
Ertaga: 2025-05-09


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [47]:
days = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')

print(days)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [48]:
arr=np.random.randint(251, size=(10))
a=arr-arr%12
b=np.floor(arr)
c=arr.astype(int)
d=np.trunc(arr)


print("\n1-usul (%):", a)
print("\n2-usul (floor):", b)
print("\n3-usul (astype):", c)
print("\n4-usul (trunc):", d)


1-usul (%): [156 120   0 108 192  36 180  60  48 216]

2-usul (floor): [160. 125.   2. 119. 195.  41. 182.  70.  59. 224.]

3-usul (astype): [160 125   2 119 195  41 182  70  59 224]

4-usul (trunc): [160. 125.   2. 119. 195.  41. 182.  70.  59. 224.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [66]:
import time


assiv = np.random.randint(1000000, size=1000000)

def vaqtni_olchash(func, arr):
   start = time.time()
   result = func(arr)
   stop = time.time()
   return result, stop - start

sum_natija, sum_vaqt = vaqtni_olchash(np.sum, arr)
print(f"np.sum natijasi: {sum_natija}, vaqti: {sum_vaqt}")

reduce_natija, reduce_vaqt = vaqtni_olchash(np.add.reduce, arr)

print(f"np.add.reduce natijasi: {reduce_natija}, vaqti: {reduce_vaqt}")
print(f"np.add.reduce usuli np.sum dan {sum_vaqt/reduce_vaqt:.2f} marta tezroq")

np.sum natijasi: 1177, vaqti: 3.695487976074219e-05
np.add.reduce natijasi: 1177, vaqti: 1.4781951904296875e-05
np.add.reduce usuli np.sum dan 2.50 marta tezroq


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [71]:
arr = np.array([1, 2, 3, 4, 5])
c = np.zeros(len(arr) + (len(arr)-1) * 3)
c[::4] = arr
print(c)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [7]:
from numpy.lib import stride_tricks


a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
b = stride_tricks.as_strided(a, shape=(11, 4), strides=(a.itemsize, a.itemsize))

print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [8]:
arr = np.array([5, 2, 8, 5, 1, 9, 2, 5, 3, 2, 9])

sanash = np.bincount(arr)
eng_kop_takrorlangan = np.argmax(sanash)
print("Eng ko'p takrorlangan qiymat:", eng_kop_takrorlangan)
print("Takrorlanish soni:", sanash[eng_kop_takrorlangan])

Eng ko'p takrorlangan qiymat: 2
Takrorlanish soni: 3


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [20]:
arr=np.random.randint(25, size=(3,3))
tr = arr.T
print("\nTransponirlangan massiv:")
print(tr)
print("\nAsosiy massiv:")
print(arr)


Transponirlangan massiv:
[[ 1 13 21]
 [22  4 24]
 [16 21 16]]

Asosiy massiv:
[[ 1 22 16]
 [13  4 21]
 [21 24 16]]
